# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tirth/Classes/Midterms_ECE3300/FaultAnalyzer/FaultAnalyzer.srcs/sources_1/ip/fifo_event_buffer/fifo_event_buffer.xci
# IP: The module: 'fifo_event_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tirth/Classes/Midterms_ECE3300/FaultAnalyzer/FaultAnalyzer.gen/sources_1/ip/fifo_event_buffer/fifo_event_buffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_event_buffer'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/tirth/Classes/Midterms_ECE3300/FaultAnalyzer/FaultAnalyzer.gen/sources_1/ip/fifo_event_buffer/fifo_event_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_event_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/tirth/Classes/Midterms_ECE3300/FaultAnalyzer/FaultAnalyzer.srcs/sources_1/ip/fifo_event_buffer/fifo_event_buffer.xci
# IP: The module: 'fifo_event_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tirth/Classes/Midterms_ECE3300/FaultAnalyzer/FaultAnalyzer.gen/sources_1/ip/fifo_event_buffer/fifo_event_buffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_event_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/tirth/Classes/Midterms_ECE3300/FaultAnalyzer/FaultAnalyzer.gen/sources_1/ip/fifo_event_buffer/fifo_event_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_event_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
